version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: "pipes"
  relay_timeout: "20s"

kafka:
  brokers: kafka:9092

jobs:
  pool:
    debug: true
    command: "php app.php"
    num_workers: 1
  consume:
    - kafka_test
  pipelines:
    kafka_test:
      driver: kafka
      config:
        priority: 1
        auto_create_topics_enable: true
        producer_options:
          max_message_bytes: 1000
          required_acks: LeaderAck
          compression_codec: snappy
          disable_idempotent: true
        consumer_options:
          topics: [ "kafka_test" ]
        group_options:
          group_id: rr_consumer

logs:
  mode: development
  level: debug
  encoding: console
